### ISSUE TITLE
one·一个好像挂了？

### ISSUE THREAD

**Issue by 1761178412** [weekend-project-space/top-rss-list#17]
好像半个月没更新了，订阅链接打开也提示
Looks like something went wrong
Helpful Information

Error Message:

wrong path
Route: /one

Full Route: /one

Node Version: v21.7.1

Git Hash: 7881250f

Git Date: Thu, 14 Mar 2024 17:53:48 GMT

**Comment by weekend-project-space** [comment]
源挂了的话建议换个源
