### ISSUE TITLE
批量导入

### ISSUE THREAD

**Issue by Stick-of-WuKong** [weekend-project-space/top-rss-list#20]
有没有opml文件 一个一个复制太麻烦了

**Comment by Fiber-Five** [comment]
是啊，整体导入，删除不要的，逐个添加也不知道每个质量咋样

**Comment by yiGmMk** [comment]
看看下面这个格式可用不,写了个脚本解析
<opml version="2.0">
  <head>
    <title>RSS Feeds</title>
  </head>
  <body>
    <outline text="阮一峰的网络日志" type="rss" xmlUrl="https://www.ruanyifeng.com/blog/atom.xml"></outline>
    <outline text="阮一峰的网络日志" type="rss" xmlUrl="http://feeds.feedburner.com/ruanyifeng"></outline>
    <outline text="少数派" type="rss" xmlUrl="https://sspai.com/feed"></outline>
    <outline text="美团技术团队" type="rss" xmlUrl="https://rsshub.app/meituan/tech/home"></outline>
    <outline text="V2EX" type="rss" xmlUrl="https://v2ex.com/index.xml"></outline>
    <outline text="南方周末-新闻" type="rss" xmlUrl="https://rsshub.app/infzm/2"></outline>
    <outline text="机核" type="rss" xmlUrl="https://www.gcores.com/rss"></outline>  
</body>
</opml>

**Comment by yiGmMk** [comment]
看下这个格式可用不,写了个脚本解析 

https://github.com/yiGmMk/top-rss-list/blob/ecebcb6c5f2e7b886da9da05fa18ee501c11ca89/feeds.opml

**Comment by weekend-project-space** [comment]
[toprss.webfollow.cc](https://toprss.webfollow.cc/) 花了半天写了一个功能
