### ISSUE TITLE
经常掉线并要求重新登陆，以及其他问题

### ISSUE THREAD

**Issue by FeiLZX3Km** [weekend-project-space/top-rss-list#7]
1. 开发者你好，在操作比较频繁的状态下，账号很容易掉线并要求重新登陆，约几分钟就会掉线。因此在打开此网页服务的同时，必须同时打开相应的邮箱界面两个网页承便实时接收验证码，很不方便，我今天下午仅登陆验证码就已经接收超过十个了。个人认为此问题已经严重到可以认定为bug的程度了。期待开发者能够修复此问题。
3. 取消订阅界面很难找。因为新手进入界面分不清两个工作模式，所以找不到取消订阅在哪里。希望开发者能够将在设置界面，额外添加一个取消订阅的功能按钮。

**Comment by weekend-project-space** [comment]
问题已收到，会及时更新并反馈的，感谢反馈

**Comment by weekend-project-space** [comment]
第一个问题应该是赶上发布更新的时间，
第二个问题在channel界面增加了订阅/取消订阅的按钮
